"""auto-vote

Revision ID: d885cdda392b
Revises: 21c147685e5d
Create Date: 2022-03-29 15:34:04.930826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd885cdda392b'
down_revision = '21c147685e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
